### ISSUE TITLE
Forward Qt dependency in .pc

### ISSUE THREAD

**Issue by nim65s** [Gepetto/gepetto-viewer#104]
Hi,

When a dependency of this package tries to import `config-osg.h`, it fails on the following line:

https://github.com/Gepetto/gepetto-viewer/blob/26a29ebaff86a7fa146d2dcf31184a02df601fe3/include/gepetto/viewer/config-osg.h#L13

e.g. in http://robotpkg.openrobots.org/rbulk/robotpkg-wip/wip/openhrp3-simulator-wo-rtm/openhrp3-simulator-wo-rtm-1.2.0/Ubuntu-16.04-x86_64/build.html :
```
/opt/openrobots/include/gepetto/viewer/config-osg.h:13:21: fatal error: QMetaType: No such file or directory
```
So I think we should add a `Cflags` with `-I${QT_QTCORE_INCLUDE_DIR}` in the .pc.

(I still have to check if this is the same for Qt5)

**Comment by jmirabel** [comment]
@nim65s I close this since there hasn't been any activity. Feel free to re-open if needed.
