### ISSUE TITLE
Plugin loading

### ISSUE THREAD

**Issue by nim65s** [Gepetto/gepetto-viewer#131]
Hi,

Running `gepetto-gui`, with gepetto-viewer & gepetto-viewer-corba raised the following errors:
```
"omniorbserver.so" :  "The shared library was not found."
Plugin "omniorbserver.so" not loaded: "The shared library was not found."
```

This .so is available at `/usr/lib/gepetto-gui-plugins`, so setting `QT_PLUGIN_PATH` to this path fixed the issue for me.

But depending on how I build GV & GV-corba, this is sometimes required and sometimes not.

Without this `QT_PLUGIN_PATH`, how is the plugin system able to find the plugins ?

**Comment by jmirabel** [comment]
It looks for the plugin in *<path>/gepetto-gui-plugins* for each *path* in *LD_LIBRARY_PATH*.

**Comment by nim65s** [comment]
Thanks, I understand better.

**Comment by jmirabel** [comment]
I agree that the list of searched path is not exhaustive. Any suggestion is welcome.

**Comment by nim65s** [comment]
I'd suggest to just add `${CMAKE_INSTALL_PREFIX}/lib/gepetto-gui-plugins`, and add a hint for `GEPETTO_GUI_PLUGIN_DIRS` in the error message.
