### ISSUE TITLE
No package 'openscenegraph' found

### ISSUE THREAD

**Issue by YunxiTang** [Gepetto/gepetto-viewer#164]
when i try to build gepetto-viewer, the error raised that 'No package 'openscenegraph' found' . but i actually already installed openscenegraph. As osgversion command works well on  my linux system.

**Comment by jmirabel** [comment]
How did you install openscenegraph and which version did you install ?
openscenegraph is found with pkgconfig so you should have a valid PKG_CONFIG_PATH.

**Comment by YunxiTang** [comment]
i use sudo install  to install openscenegraph.

**Comment by florent-lamiraux** [comment]
Can you type `dpkg -l | grep openscenegraph` on your machine and copy paste the result here ?

**Comment by jmirabel** [comment]
> i use sudo install to install openscenegraph.

I asked for the version as well. I think it is because you didn't install the development package of openscenegraph.

**Comment by tlemarec** [comment]
Hello, same problem here.
I used `sudo apt install openscenegraph` and `dpkg -l | grep openscenegraph` returns :
```
ii  libopenscenegraph160:amd64                 3.6.4+dfsg1-3build2                         amd64        3D scene graph, shared libs
ii  openscenegraph                             3.6.4+dfsg1-3build2                         amd64        3D scene graph, utilities and examples (binaries)
```

**Comment by nim65s** [comment]
This is missing the development package: can you try again after `sudo apt install libopenscenegraph-dev`  ?

**Comment by tlemarec** [comment]
This worked thanks
