### ISSUE TITLE
Robotpkg packaging

### ISSUE THREAD

**Issue by jmirabel** [Gepetto/gepetto-viewer#186]
Hi @nim65s,

Could you update gepetto-viewer binaries on robotpkg:
- [ ] to include QCustomPlot (`cmake -DBUILD_PY_QCUSTOM_PLOT=ON` should be sufficient) and
- [ ] to add `oxygen-icon-theme` as an apt dependency ?

For the record, QCustomPlot license is GPL and it is included in gepetto-viewer as a plugin. It does not change the license of gepetto-viewer. It implies that Python plugins based on QCustomPlot are GPL.

**Comment by jmirabel** [comment]
Hi @nim65s 
Would you have time to do this ?

**Comment by nim65s** [comment]
First part is trivial and will be handled soon. For the second, I am not sure yet, but I'll check with the first :)

**Comment by nim65s** [comment]
I think this is OK now. @jmirabel : could you confirm and close this ?

**Comment by jmirabel** [comment]
I guess it's fine. I haven't had the chance to test yet. I'll re-open if there is an issue.

Thank you.
