### ISSUE TITLE
Release 

### ISSUE THREAD

**Issue by jcarpent** [Gepetto/gepetto-viewer#69]
@nim65s Why release version has made such big jump?

**Comment by nim65s** [comment]
Hi,

This version number is the same for HPP packages that has been released together. It might not be a good decision, but when I see the time I need to release everything, I try to simplify the work.

A better solution would probably be to transfer gepetto-viewer & gepetto-viewer-server from HPP to Gepetto

**Comment by nim65s** [comment]
Done
