### ISSUE TITLE
error: ‘ObjectCache’ is not a member of ‘osgDB’

### ISSUE THREAD

**Issue by nim65s** [Gepetto/gepetto-viewer#80]
Hi,

Since #77, I can't build devel:
```
/local/users/gsaurel/gepetto/gepetto-viewer/src/leaf-node-collada.cpp: In member function ‘void graphics::LeafNodeCollada::init()’:
/local/users/gsaurel/gepetto/gepetto-viewer/src/leaf-node-collada.cpp:59:27: error: ‘ObjectCache’ is not a member of ‘osgDB’
       static osg::ref_ptr<osgDB::ObjectCache> object_cache (new osgDB::ObjectCache);
                           ^
```

This error could have been prevented by checking the CI: 
https://gepgitlab.laas.fr/gepetto/gepetto-viewer/pipelines/3113/builds

This error prevents the CI of hpp-doc to pass: https://gepgitlab.laas.fr/gsaurel/hpp-doc/-/jobs/12087.

**Comment by jmirabel** [comment]
Hum, I think I know the issue. I'll have a look.

**Comment by nim65s** [comment]
Thanks :)

For now, on 16.04 / osg 3.2.1, I only found `ObjectCache` as a protected member of `osgDB::Registry`

**Comment by jmirabel** [comment]
It was introduced somewhere between 3.2.1 and 3.4...

**Comment by nim65s** [comment]
In 3.3.3: https://github.com/openscenegraph/OpenSceneGraph/commit/ed28ec97c708e31ea9030f2d88f3d0ace0e97baf#diff-b0eed203a64adbb82d6b2d33f3a5215c
