### ISSUE TITLE
Missing plugins/CMakeLists.txt file

### ISSUE THREAD

**Issue by nim65s** [Gepetto/gepetto-viewer#86]
Hi,

https://github.com/Gepetto/gepetto-viewer/blob/0e80cda20be7d49f8a24b2b848e3c0289c10d722/CMakeLists.txt#L161

So I think that either @jmirabel forgot to commit a file, or that  we should instead include invidiual plugins.

**Comment by jmirabel** [comment]
Thanks for the report. I pushed directly on devel branch.
