### ISSUE TITLE
compile error s about osg

### ISSUE THREAD

**Issue by xuhuairuogu** [Gepetto/gepetto-viewer#93]
My environment is Ubuntu16.04 and I have installed openrave and openscenegraph3.2.1. The cmake can detect the openscenegraph successfully:
![cmake](https://user-images.githubusercontent.com/10009476/58325560-a9a89700-7e5c-11e9-9eb2-7b5c00e62112.png)
However, errors occur during the compiling like the following :
![error](https://user-images.githubusercontent.com/10009476/58325467-6cdca000-7e5c-11e9-9c88-fa58a8447f30.png)

**Comment by jmirabel** [comment]
The error message alone isn't enough. You must also provide the compilation command (last call to g++ before error, using `VERBOSE=1 make`).

**Comment by xuhuairuogu** [comment]
![error](https://user-images.githubusercontent.com/10009476/58326266-e70e2400-7e5e-11e9-9c59-c1ba88a152b2.png)

**Comment by jmirabel** [comment]
Do you have several versions of OpenSceneGraph installed ?

**Comment by xuhuairuogu** [comment]
I search libosg and find there exists several versions.

**Comment by jmirabel** [comment]
Then this is your issue. I think there is a missing `-L` option to the compilation command. Stackoverflow will be a better help for finding out how to solve your issue.

**Comment by jmirabel** [comment]
I close because I believe this is not related to GV. Please, re-open if necessary.
